# Linear Algebra — Hands-On

**What you'll do here:**

1. Create scalars, vectors, matrices, and tensors in NumPy
2. Practice all 5 matrix operations: add, transpose, scalar mult, element-wise mult, matrix mult
3. Use these operations to **manually compute the output of a single neuron** - the heart of every neural network

Everything here matches the videos. Same notation, same examples, just in code.

## 0. Setup

In [2]:
# !pip install numpy -q

In [3]:
import numpy as np

print("NumPy version:", np.__version__)

NumPy version: 2.0.2


## 1. The 4 Data Shapes

Recall from the video — every piece of data in a neural network is one of these 4 shapes:

| Shape  | Dim | Example use            |
|--------|-----|------------------------|
| Scalar | 0D  | learning rate, loss    |
| Vector | 1D  | word embedding         |
| Matrix | 2D  | weight matrix, input X |
| Tensor | nD  | RGB image, batch of images |

Let's create one of each and check its `.shape`.

1.1. Scalar (0D)

In [6]:
# a single number
learning_rate = np.array(0.01)

print("value:", learning_rate)
print("shape:", learning_rate.shape)   # () -> 0 dimensional
print("ndim:", learning_rate.ndim)

value: 0.01
shape: ()
ndim: 0


1.2. Vector (1D)

In [7]:
# a list of numbers; eg: word embedding
cat_embedding = np.array([0.1, 0.3, -0.2, 0.8])

print("value:", cat_embedding)
print("shape:", cat_embedding.shape)   # (4,) means 4 numbers in a 1D vector
print("ndim :", cat_embedding.ndim)

value: [ 0.1  0.3 -0.2  0.8]
shape: (4,)
ndim : 1


### 1.3 Matrix (2D)

This is the same matrix from the video — a (3, 2) weight matrix:

$$W = \begin{bmatrix} 2 & 3 \\ 4 & 5 \\ 6 & 7 \end{bmatrix}$$

In [9]:
W = np.array([
    [2, 3],
    [4, 5],
    [6, 7]
])

print("matrix:\n", W)
print("shape :", W.shape)   # (3, 2) -> 3 rows, 2 columns
print("ndim  :", W.ndim)

matrix:
 [[2 3]
 [4 5]
 [6 7]]
shape : (3, 2)
ndim  : 2


### 1.4 Tensor (nD)

An RGB image is a 3D tensor with shape `(height, width, channels)`. Let's create a tiny 4×4 "image" with 3 channels.

In [13]:
# random pixel values - pretend this is a 4x4 matrix
image = np.random.rand(4, 4, 3)

print("shape:", image.shape)
print("ndim:", image.ndim)

# A batch of 32 such images (like one training batch) -> (32, 4, 4, 3)
batch = np.random.rand(32, 4, 4, 3)
print("\nbatch shape:", batch.shape)
print("batch ndim:", batch.ndim)

shape: (4, 4, 3)
ndim: 3

batch shape: (32, 4, 4, 3)
batch ndim: 4


## 2. The 5 Matrix Operations

Same examples as the video — let NumPy verify our hand-calculations.

### 2.1 Addition & Subtraction

**Rule:** Shapes must match. It's element-wise.

$$A = \begin{bmatrix} 2 & 3 \\ 4 & 1 \end{bmatrix}, \quad B = \begin{bmatrix} 1 & 0 \\ 2 & 5 \end{bmatrix}$$

In [14]:
A = np.array([
    [2, 3],
    [4, 1]
])

B = np.array([
    [1, 0],
    [2, 5]
])

sum = A + B
difference = A - B

print("A + B =\n", sum)
print("\nA - B =\n", difference)

A + B =
 [[3 3]
 [6 6]]

A - B =
 [[ 1  3]
 [ 2 -4]]


## 2.2 Transpose — flip rows ↔ columns

In [15]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

A_T = A.T

print("A shape  :", A.shape)    # (2, 3)
print("A:\n", A)

print("\nA.T shape:", A_T.shape)  # (3, 2)
print("A.T:\n", A_T)

A shape  : (2, 3)
A:
 [[1 2 3]
 [4 5 6]]

A.T shape: (3, 2)
A.T:
 [[1 4]
 [2 5]
 [3 6]]


### 2.3 Scalar Multiplication

$$\alpha = 0.01, \quad W = \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}$$

In [16]:
alpha = 0.01
W = np.array([[1, 2],
              [3, 4]])

print("alpha * W =\n", alpha * W)

alpha * W =
 [[0.01 0.02]
 [0.03 0.04]]


### 2.4 Element-wise Multiplication (denoted `⊙`)

Multiply matching positions. Different from matrix multiplication!

In [17]:
A = np.array([[2, 3],
              [4, 1]])

B = np.array([[1, 0],
              [2, 5]])

# In NumPy, the * operator on arrays is element-wise (NOT matrix mult)
print("A ⊙ B =\n", A * B)

A ⊙ B =
 [[2 0]
 [8 5]]


### 2.5 Matrix Multiplication — the big one

**Rule:** inner dims must match. `(m × n) · (n × p) = (m × p)`.

Same example from the video:

$$A = \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}, \quad B = \begin{bmatrix} 5 & 6 \\ 7 & 8 \end{bmatrix}$$

In [18]:
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

# Use @ for matrix multiplication (or np.matmul / np.dot)
result = A @ B

print("A @ B =\n", result)
print("shape:", result.shape)

A @ B =
 [[19 22]
 [43 50]]
shape: (2, 2)


Expected from the video:
$$\begin{bmatrix} 19 & 22 \\ 43 & 50 \end{bmatrix}$$
Matches ✓

Let's manually verify just one cell — top-left `(1×5) + (2×7) = 5 + 14 = 19` ✓

### Mini-exercise: catch a shape mismatch

Try multiplying two matrices whose inner dimensions don't match. NumPy will yell at you — get used to reading these errors.

In [23]:
P = np.random.rand(3, 4)    # shape (3, 4)
Q = np.random.rand(5, 2)    # shape (5, 2)


try:
  print("P @ Q:\n", P @ Q)
except ValueError as e:
  print("error caught", e)

error caught matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 5 is different from 4)


## 3. Putting it together — A Single Neuron's Forward Pass

From the video: a single neuron computes

$$z = w \cdot x + b \quad\rightarrow\quad \hat{y} = \sigma(z)$$

Let's build it. Inputs: 3 features. Weights: 3 values. One bias. One sigmoid activation.

In [26]:
# inputs
x = np.array([0.5, 0.2, 0.9])   # 3 input features

# parameters
w = np.array([0.4, -0.3, 0.8])  # 3 weights (one per feature)
b = 0.1

print("x shape:", x.shape)
print("w shape:", w.shape)


# step 1: Linear combination: z = w.x + b
z = w @ x + b
print("\nz=", z)

# step 2: activation y_hat = sigmoid(x)
def sigmoid(value):
  return 1 / (1 + np.exp(-value))

y_hat = sigmoid(z)
print("\ny_hat=", y_hat)

x shape: (3,)
w shape: (3,)

z= 0.9600000000000001

y_hat= 0.7231218051243898


## 4. Scaling up — A Hidden Layer with 4 Neurons

Now instead of 1 neuron, we have a layer of 4 neurons all looking at the same input. The weights become a *matrix*.

$$Z = W \cdot x + b$$

- `x` : shape `(3,)`  — 3 input features
- `W` : shape `(4, 3)` — 4 neurons, each with 3 weights
- `b` : shape `(4,)`  — one bias per neuron
- `Z` : shape `(4,)`  — output of the layer

In [27]:
x = np.array([.5, 0.2, 00.9])           # 3 features

W = np.array([                            # 4 neurons × 3 weights
    [ 0.4, -0.3,  0.8],
    [ 0.1,  0.6, -0.2],
    [-0.5,  0.2,  0.4],
    [ 0.7,  0.0, -0.1]
])

b = np.array([0.1, -0.1, 0.0, 0.2])      # one bias per neuron

# Forward pass — entire layer in ONE matrix multiplication
Z = W @ x + b
A = sigmoid(Z)

print("Z (pre-activation):", Z)
print("A (post-activation):", A)
print("\nOutput shape:", A.shape, "-> 4 neurons, 4 activations")

Z (pre-activation): [ 0.96 -0.11  0.15  0.46]
A (post-activation): [0.72312181 0.4725277  0.53742985 0.61301418]

Output shape: (4,) -> 4 neurons, 4 activations


That single line `Z = W @ x + b` is what every deep learning framework (PyTorch, TensorFlow) runs millions of times per second under the hood. Now you know what it actually does.

## 5. Recap — Where Each Operation Shows Up in DL

| Operation        | Where it's used                              |
|------------------|----------------------------------------------|
| `W @ x`          | forward pass                                  |
| `W @ x + b`      | adding bias                                   |
| `α · ∇w`         | applying learning rate (scalar mult)          |
| `a ⊙ b`          | dropout, gating (element-wise mult)           |
| `W.T`            | backpropagation through a linear layer        |

**In the next notebook:** we'll see how *calculus* tells us which direction to nudge each `W` value to reduce loss. That's where gradients come in.